# Generated by Django 2.2.6 on 2019-10-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album',
            new_name='images',
        ),
    ]
