# Generated by Django 2.2.6 on 2019-10-23 01:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20191022_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='images/'), size=None),
        ),
    ]
