# Generated by Django 2.2.6 on 2019-10-23 02:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20191023_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
